name: Lint On Pull

on:
  pull_request:
    branches:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 20
          repository: q-13t/ci_cd_test
          token: ${{ secrets.PAT }}
        permissions:
          contents: read
      - run: npm ci
      - run: npm lint
      - run: npm build
